In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
tree = pd.read_csv('../Data/tree_algorithm/set_tree.csv')
sdf = pd.read_csv('../Data/tree_algorithm/set_particles.csv')
tree

        x_min    y_min     side  depth      n
0    -1.50000 -1.50000  3.00000      0  10000
1    -1.50000 -1.50000  1.50000      1   2460
2    -1.50000 -1.50000  1.50000      2   2460
3    -1.50000 -1.50000  1.50000      3   2460
4    -1.50000 -1.50000  0.09375      4      0
...       ...      ...      ...    ...    ...
3123  1.03125  1.40625  0.09375      4      0
3124  1.12500  1.40625  0.09375      4      0
3125  1.21875  1.40625  0.09375      4      0
3126  1.31250  1.40625  0.09375      4      0
3127  1.40625  1.40625  0.09375      4      0

[3128 rows x 5 columns]

In [3]:
from matplotlib.patches import Rectangle

col=["k","blue", "green" ,"blue", "green", "red", "orange", "yellow", "k"]
fig = plt.figure(figsize=(8,8))
#add rectangle
for i in range(tree.shape[0]):
    plt.gca().add_patch(Rectangle((tree["x_min"][i],tree["y_min"][i]),tree["side"][i],tree["side"][i],
                    edgecolor=col[tree["depth"][i]-1],
                    facecolor='none',
                    lw=0.8, zorder=10-tree["depth"][i]))
plt.plot(sdf['x'], sdf['y'], '.', color='k', ms=1)
#plt.xlim(0, 1)
#plt.ylim(0, 1)
plt.show()

SyntaxError: invalid syntax (3231427515.py, line 3)

In [ ]:
part = pd.read_csv('../Data/tree_algorithm/set_neighbors.csv')
particle = part["p"][0]
neightbors = part["p"][1:]

In [ ]:
fig = plt.figure(figsize=(8,8))
ax = fig.add_subplot()
plt.plot(sdf['x'], sdf['y'], '.', color='k', ms=2)
plt.plot(sdf['x'][neightbors], sdf['y'][neightbors], '.', color='blue', ms=4)
plt.plot(sdf['x'][particle], sdf['y'][particle], 'o', color='crimson', ms=5)

for i in range(tree.shape[0]):
    plt.gca().add_patch(Rectangle((tree["x_min"][i],tree["y_min"][i]),tree["side"][i],tree["side"][i],
                    edgecolor="k",
                    facecolor='none',
                    lw=0.5))

compact_domain = plt.Circle((sdf['x'][particle], sdf['y'][particle]), 2*sdf["h"][particle], color='b', fill=False)
ax.add_patch(compact_domain)
#ax.set_xlim(0, 1)
#ax.set_ylim(0, 1)
plt.show()